# Array Manipulation

In [ ]:
# reshaping array
# array fattening 
# dimennsion shuffling
# joining arrays
# splitting arrays
# add/remove elements to arrays

In [3]:
# reshaping numpy array:
     # it wont change the array data
    #syntax
    #numpy.reshape(array , shape , order) [C,A,F]
    #array name.reshape(shape , order)
# what it returns ndarray with mentioned shape
#  example
import numpy as np
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
a.shape

(9,)

In [5]:
b = np.reshape(a , (3,3))  # without using an order 
b         # we can chnge the shape of the data 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
# using an order
c = np.reshape(a , (3,3),order = "F")
c                  # it changes in ascending order

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [8]:
a.size

9

In [10]:
# resizing an array
# syntax: numpy.resize(arrayname , shape)
# example
x = np.arange(0 , 15 , 3)
x

array([ 0,  3,  6,  9, 12])

In [12]:
x.shape

(5,)

In [13]:
x.size

5

In [17]:
np.resize(x , (2,4))

array([[ 0,  3,  6,  9],
       [12,  0,  3,  6]])

In [22]:
np.resize(x , (9,45))

array([[ 0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,
         3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,
         6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12],
       [ 0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,
         3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,
         6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12],
       [ 0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,
         3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,
         6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12],
       [ 0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,
         3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,
         6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12],
       [ 0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,
         3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,  6,  9, 12,  0,  3,
         6,  9, 12,  0,  3,  6,  9, 

# Flatten and ravel

In [ ]:
#ndarray.flatten (order = "")  , CAFK,


In [23]:
y = np.array([[4,8,9] , [8 , 9, 6] , [5 , 7 , 3] , [1 , 0 , 2]])
y

array([[4, 8, 9],
       [8, 9, 6],
       [5, 7, 3],
       [1, 0, 2]])

In [24]:
y. flatten() # 3d to 1d

array([4, 8, 9, 8, 9, 6, 5, 7, 3, 1, 0, 2])

In [28]:
y.flatten(order = "F")

array([4, 8, 5, 1, 8, 9, 7, 0, 9, 6, 3, 2])

In [29]:
y.flatten(order = "C")

array([4, 8, 9, 8, 9, 6, 5, 7, 3, 1, 0, 2])

In [30]:
y.flatten(order = "K")

array([4, 8, 9, 8, 9, 6, 5, 7, 3, 1, 0, 2])

In [31]:
y.flatten(order = "A")

array([4, 8, 9, 8, 9, 6, 5, 7, 3, 1, 0, 2])

In [ ]:
# ravel array # it will copy the elmnt when it si needed

In [33]:
a = np.array([[11 , 22 ] , [54 , 65] , [45 , 65]])
a

array([[11, 22],
       [54, 65],
       [45, 65]])

In [36]:
a.ravel()

array([11, 22, 54, 65, 45, 65])

In [38]:
np.ravel(a)

array([11, 22, 54, 65, 45, 65])

In [67]:
np.ravel( a , order = "F")


array([11, 54, 45, 22, 65, 65])

In [12]:
# transpose and swapaxes
# syntax
# numpy.transpose(array , axes = none)
# example
arr1 = np .arange(1,11).reshape(5,2)
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
np.transpose(arr1)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [14]:
arr1.shape

(5, 2)

In [15]:
np.transpose(arr1).shape

(2, 5)

In [6]:
import numpy as np


In [16]:
np.transpose(arr1).shape

(2, 5)

In [19]:
# 1d array
a = np.arange(5 , 25 , 2)
a


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [20]:
np.transpose(a)  # rearrange the dimention not applicable for 1d

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [22]:
# use of axes
arr1 = np.arange(5 , 15 ,  ).reshape(5 , 2)
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [23]:
np.transpose(arr1)

array([[ 5,  7,  9, 11, 13],
       [ 6,  8, 10, 12, 14]])

In [26]:
np.transpose(arr1 ,axes = (0,1))

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [27]:
np.transpose(arr1 ,axes = (1,0))  # axes uses for 3d and 2d array

array([[ 5,  7,  9, 11, 13],
       [ 6,  8, 10, 12, 14]])

In [29]:
a = np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [31]:
a.shape

(2, 3, 4)

In [34]:
a.transpose()

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [35]:
np.transpose(a) # or practise as much

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [43]:
np.transpose(a,(0,2,1))

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [44]:
np.transpose(a,(1,2,0))   # we are giving the axes values in bracket

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [46]:
a.transpose() # equivalent method

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [50]:
# swapaxes()
np.swapaxes(a,0,1)


array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [51]:
np.swapaxes(a,1,0)  # same o/p

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [52]:
np.swapaxes(a,1,2)  

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [53]:
np.swapaxes(a,1,2).shape

(2, 4, 3)

In [55]:
a.swapaxes(1,2) # equivalent

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

###  splitting and joining arrays

In [ ]:
# joining arrays
# using concatenate
# syntax:
# numpy.concatenate(array , axis = 0 , out = none)

In [65]:
a = np.arange(1,5)
b = np.arange(6)
np.concatenate((a,b))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [67]:
c = np.arange(2)
np.concatenate((a,b,c))


array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1])

In [80]:
d = np.zeros(10)
np.concatenate((a,b),out=d)

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5.])

In [81]:
# 2d arrays
a = np.array([[4,8] , [5,7]])
b = np.array([[2,0]])
np.concatenate((a,b))

array([[4, 8],
       [5, 7],
       [2, 0]])

In [82]:
np.concatenate((a,b)).shape

(3, 2)

In [84]:
np.concatenate((a,b),axis = 1) # error appears

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [88]:
np.concatenate((a,b.T) , axis = 1) # careful of dimention and shape of the array!!

array([[4, 8, 2],
       [5, 7, 0]])

In [ ]:
#vstack():
# numpy.vstack(tuple)


In [90]:
np.vstack((a,c))

array([[4, 8],
       [5, 7],
       [0, 1]])

In [6]:
#hstack()
# np.hstack(tuple) # 2d , 3d same as 1
#import numpy as np
#np.hstack((a,n))

NameError: name 'a' is not defined

In [9]:
import numpy as np

In [11]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.split(a,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [14]:
a = np.arange(1,13).reshape(6,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [15]:
 np.split(a,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [16]:
# hsplit()
#vsplit()
# numpy.hsplit(array , section)
# numpy.hsplit(array , section)
np.vsplit(a,2) # axis = 0 so axis is not defined

[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

## insert and delete function in an given array

In [ ]:
# insert()
# numpy.insert(array , obj , values , axis = none)

In [18]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.insert(a,1,20)

array([ 1, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.insert(a,1,20.454545) # float to int ,  it converts

array([ 1, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.insert(a,(1,3),78) # to insert the 78 in 1,3 

array([ 1, 78,  2,  3, 78,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2d array

In [23]:
b = np.array([[2,5] , [8,3]])
b

array([[2, 5],
       [8, 3]])

In [26]:
np.insert(b,1,35)

array([ 2, 35,  5,  8,  3])

In [27]:
np.insert(b,1,23,axis = 0)

array([[ 2,  5],
       [23, 23],
       [ 8,  3]])

In [28]:
np.insert(a,1,[2,3] , axis = 0)

array([ 1,  2,  3,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [32]:
# append()
# numpy.append(array ,values , axis = none)
np.append(b,55)

array([ 2,  5,  8,  3, 55])

In [ ]:
# delete()
# syntax 
# numpy.delete(array , obj , axis = none)

In [33]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.delete(a,2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.delete(b,2) # check b value

array([2, 5, 3])