# DATATYPES
definition::
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype:


In [1]:
import numpy as np

In [4]:
a = np.zeros(5)
a.dtype

dtype('float64')

In [10]:
b = np.zeros(6,dtype = np.int8)
b

array([0, 0, 0, 0, 0, 0], dtype=int8)

In [13]:
x = np.float32(2)
x

2.0

In [14]:
x.dtype

dtype('float32')

In [20]:
a = np.array([2,3,4] , dtype = "f")  # using the character codes
a

array([2., 3., 4.], dtype=float32)

In [21]:
a.astype(int) # to change the type of an array

array([2, 3, 4])

In [22]:
# datatype itself ia an function
np.float64(a)

array([2., 3., 4.])

In [29]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"




<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [30]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.92803454 0.17291253]
 [0.49619183 0.91321462]]


# Indexing Operation in NumPy Arrays

In [ ]:
# can retrieve single value of array
# zero based indexing
# negative indexing
# 1d array


In [31]:
# amulyas academy
a = np.array([7,8,9,4,5,6])
a

array([7, 8, 9, 4, 5, 6])

In [32]:
a[3]

4

In [33]:
a[-5]

8

In [34]:
a[-0]

7

In [35]:
a[0]

7

In [36]:
# 2dimentional array
b = np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b [1][2] # dont ,mix it with +,-

6

In [44]:
b[-1][2]

6

In [ ]:
# 3dimentional array   i ,  j , k  <>  

In [62]:
c =[[1,2,3,4], [5,6,7,8], [9,10,11,12]]
c
d = np.array(c)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
d[1:2]

array([[5, 6, 7, 8]])

# slicing operation

In [2]:
# to retrieve the collection values
import numpy as np

In [4]:
# 1d
# array_name[start:end:step]
a = np.array([1 , 2 , 3 , 4 , 5])
a

array([1, 2, 3, 4, 5])

In [5]:
a[1:4:1] # start : end : step

array([2, 3, 4])

In [6]:
a[:] # all the elements

array([1, 2, 3, 4, 5])

In [7]:
a[1::2]

array([2, 4])

In [8]:
a[:3]

array([1, 2, 3])

In [ ]:
# 2dimentional array
a[s,e,ste , st,e,ste]

In [21]:
y = np.array([[4,5,5,8] , [7,8,9,7] , [1,2,3,1]])
y

array([[4, 5, 5, 8],
       [7, 8, 9, 7],
       [1, 2, 3, 1]])

In [22]:
y[0:,0:]

array([[4, 5, 5, 8],
       [7, 8, 9, 7],
       [1, 2, 3, 1]])

In [31]:
y[1::,:2]

array([[7, 8],
       [1, 2]])

In [ ]:
# 3dimentional array
# syntax a[s:e:s , s:e:s , s:e:s]

In [40]:
z = np.array([[14,25,75,8] , [17,28,39,7] , [1,52,3,1] ,[1,2,3,1] ,[7,8,9,7]  ])
z

array([[14, 25, 75,  8],
       [17, 28, 39,  7],
       [ 1, 52,  3,  1],
       [ 1,  2,  3,  1],
       [ 7,  8,  9,  7]])

In [44]:
z[1:3:1]

array([[17, 28, 39,  7],
       [ 1, 52,  3,  1]])

## Array Math

In [45]:
import numpy as np

In [55]:
x = np.array([[4 , 5 , 6] , [ 2 , 5, 6]] , dtype = np.float64)
y = np.array([[8 , 1 , 3] , [ 3 , 5, 6]],dtype = np.float64)

In [56]:
print(x+y)  # additon

[[12.  6.  9.]
 [ 5. 10. 12.]]


In [58]:
print(np.add(x,y)) #  same

[[12.  6.  9.]
 [ 5. 10. 12.]]


In [ ]:
# subtraction

In [59]:
print(x-y)

[[-4.  4.  3.]
 [-1.  0.  0.]]


In [60]:
print(np.subtract(x,y))

[[-4.  4.  3.]
 [-1.  0.  0.]]


In [ ]:
# multiplication

In [61]:
print(x*y)

[[32.  5. 18.]
 [ 6. 25. 36.]]


In [63]:
print(np.multiply(x,y))

[[32.  5. 18.]
 [ 6. 25. 36.]]


In [65]:
help(np.math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of

In [66]:
print(x / y)

[[0.5        5.         2.        ]
 [0.66666667 1.         1.        ]]


In [67]:
print(np.divide(x, y))

[[0.5        5.         2.        ]
 [0.66666667 1.         1.        ]]


In [68]:
print(np.sqrt(x))

[[2.         2.23606798 2.44948974]
 [1.41421356 2.23606798 2.44948974]]


# Advanced indexing

In [ ]:
## indexing + slicing = basic indexing in numpy
# can access elemnts of an array repeatedly
# index should be an index array


In [71]:
# 1 dimentional array
a = np .arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
index = np.array([1,4,8])
a[index + 2]

array([ 4,  7, 11])

In [78]:
# 2 dimensional array

b = np.array([[1 , 2 , 3 ], [4 , 5 , 6] , [7 , 8 , 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
b[[0,2],[2,0]]

array([3, 7])

# Broadcasting

In [ ]:
# sterch the array
# used for array in diff size and shape

In [87]:
a = np.array([10,20,30])
b = np.array([5 , 5 , 6 , 0])

In [90]:
#  checking the shape
a.shape
b.shape

(4,)

In [91]:
a+b  # error comes

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [34]:
# broadcasting rules
# size of the dim should same
# size of the dim should be 1
# If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
# The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
# The arrays can be broadcast together if they are compatible in all dimensions.
# After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
# In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


In [97]:
import numpy as np

In [92]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
v = np.array([1, 0, 1])
v

array([1, 0, 1])

In [96]:
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
