## Matrix_Numpy

In [ ]:
# implement using nested lst , numpy arrays , matrix fn

In [6]:
# matrix addition
import numpy as np  
a = np.array([[5,7] , [7,2]])
b = np.array([[7,7] , [8,2]])
a+b

array([[12, 14],
       [15,  4]])

In [7]:
a

array([[5, 7],
       [7, 2]])

In [8]:
b

array([[7, 7],
       [8, 2]])

In [9]:
# matrix mulltiplication
# use method dot


In [10]:
a*b  # this is array multiplication ,element element by operation

array([[35, 49],
       [56,  4]])

In [12]:
a.dot(b)   # matrix multiplication

array([[91, 49],
       [65, 53]])

In [13]:
help(np.dot)

Help on built-in function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
 

In [15]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
a
# do the example

array([[1, 0],
       [0, 1]])

In [16]:
np.transpose(a)

array([[1, 0],
       [0, 1]])

In [18]:
a.transpose() # equivalent way

array([[1, 0],
       [0, 1]])

# matrix class in numpy
### np.matrix(data , dtype = none , copy = true)
#### use double quotes

In [19]:
a = np.matrix(" 1 2 ; 3 4")
a   # method to create a matrix

matrix([[1, 2],
        [3, 4]])

In [20]:
b = np.matrix([[75 , 2] , [8,3]])
b

matrix([[75,  2],
        [ 8,  3]])

In [21]:
a  + b

matrix([[76,  4],
        [11,  7]])

In [22]:
a*b  # we can use asterisk symbol to multiply # this can be created using string notation ie, ;

matrix([[ 91,   8],
        [257,  18]])

In [23]:
a.dot(b)  # bcoz we are using matrix class

matrix([[ 91,   8],
        [257,  18]])

In [ ]:
# use help(np.matrix)

## inverse of a matrix

In [ ]:
# linear algebra
# numpy.linalg .inv(a)  ,, a can  be an array
# power of matrix 
# determinants
# invert
#linear eqn

In [24]:
a = np.array([[1,3] , [5,2]])
a

array([[1, 3],
       [5, 2]])

In [31]:
b = np.linalg.inv(a)

In [32]:
b

array([[-0.15384615,  0.23076923],
       [ 0.38461538, -0.07692308]])

In [34]:
np.dot(a,b)

array([[ 1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [35]:
np.allclose(np.dot(a,b) , np.eye(2))

True

### power of a matrix

In [ ]:
# numpy.linalg.matrix_pow(a,n)
# n = 0 identity matrix
# n>0
# n<0 inverse

In [39]:
a = np.array([[1,2] , [3,4]])
a


array([[1, 2],
       [3, 4]])

In [44]:
np.linalg.matrix_power(a,3)

array([[ 37,  54],
       [ 81, 118]])

In [45]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [48]:
np.dot(a,3)

array([[21, 30],
       [45, 66]])

In [49]:
np.linalg.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [51]:
np.linalg.matrix_power(a,-2)

array([[ 39.625 , -18.125 ],
       [-27.1875,  12.4375]])

In [53]:
b = np.linalg.inv(a)
b

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [ ]:
# solving the linear equation
#  x+y = 10
#  2x+y = 5
# numpy.linalg.solve(a,b)

In [63]:
a = np.array([[5,3] , [5, 7]]) # this is the quations of 1 nd 2 variables
 b = np.array([6,2])  #this is the =" "
a

array([[5, 3],
       [5, 7]])

In [61]:
b

array([[6, 2]])

In [64]:
np.linalg.solve(a,b) # x , y

array([ 1.8, -1. ])

In [ ]:
# determinant of a matrix

In [ ]:
# numpy.linalg.det(a)  # determinant syntax

In [67]:
a = np.array([[1,4] , [3,1]])
a

array([[1, 4],
       [3, 1]])

In [68]:
np.linalg.det(a)

-11.000000000000002

In [69]:
# round usind round function
round(np.linalg.det(a))

-11.0

In [70]:
int(round(np.linalg.det(a)))

-11

In [71]:
# 3 x 3 matrix<>
b = np.array([[5 , 2 , 8 ] ,[4,2,3] , [5,3,1]])
b

array([[5, 2, 8],
       [4, 2, 3],
       [5, 3, 1]])

In [72]:
np.linalg.det(b)

3.000000000000005

In [73]:
round(np.linalg.det(b))

3.0

In [74]:
int(round(np.linalg.det(b)))

3